INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Humbert', 'de Lambilly', 589615.25);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Antoine', 'de Lambilly', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Laure', 'Pauvert', 98269.21);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Thibault', 'de Lambilly', 98269.21);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Oriane', 'de Lambilly', 98269.21);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Denis', 'de Lambilly', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Hughes', 'de Lambilly', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Arnault', 'de Lambilly', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Solène', 'de Lambilly', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Thomas', 'de Lambilly', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Mathieu', 'de Lambilly', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Anne', 'Dielaine', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Eric', 'Dielaine', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Marc', 'de Lambilly', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Charles-Edouard', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Vencelas', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Marie-Elionore', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Grégoire', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Berenice', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Thaïs', 'de Lambilly', 49134.60);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Francoise', 'de Lambilly', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Caroline', 'Nachef', 73701.91);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Marianne', 'Bedard', 73701.91);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Alexandra', 'Nachef', 73701.91);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Erwan', 'Nachef', 73701.91);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Isabelle', 'de Villele', 294807.63);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Gaëtan', 'de Villele', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Ombline', 'de Villele', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Edwige', 'de Villele', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Inès', 'de Villele', 58961.53);
INSERT INTO `person` (`firstname`, `lastname`, `share`) VALUES ('Delphine', 'de Villele', 58961.53);
