<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Poll;

/**
 * PollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByPersonId($questionId, $personId = 0)
    {

        $sql = 'SELECT p as nbr FROM ' . Poll::CLASS_NAME . ' p '
            . ' WHERE p.question = :qId AND p.person = :pId';

        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('qId', $questionId);
        $query->setParameter('pId', $personId);

        return $query->getResult()[0] ?? null;

    }
}
